[package]
name = "smooth-bevy-cameras"
description = "Bevy camera controllers with buttery, exponential smoothing."
version = "0.1.0"
repository = "https://github.com/bonsairobo/smooth-bevy-cameras"
authors = ["Duncan <bonsairobo@gmail.com>"]
keywords = ["bevy", "camera"]
edition = "2018"
license = "MIT"

[dependencies]
approx = "0.4"
serde = "1.0"

[dependencies.bevy]
version = "0.5"
features = ["render"]
default-features = false

[dev-dependencies.bevy]
version = "0.5"
features = ["bevy_winit", "bevy_wgpu", "bevy_gltf"]
default-features = false

[target.'cfg(target_os = "linux")'.dev-dependencies.bevy]
version = "0.5"
features = ["x11", "wayland"]
default-features = false
