[package]
name = "smooth-bevy-cameras"
version = "0.1.0"
authors = ["Duncan <bonsairobo@gmail.com>"]
edition = "2018"

[dependencies]
approx = "0.4"
serde = "1.0"

[dependencies.bevy]
version = "0.5"
features = ["render"]
default-features = false

[dev-dependencies]
bevy = { version = "0.5", default-features = false, features = ["render", "bevy_winit", "bevy_wgpu", "bevy_gltf"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
bevy = { version = "0.5", default-features = false, features = [ "x11", "wayland" ] }
